### ISSUE TITLE
Compare Performance between StyleSinger and DiffSinger, Compare about architures,v.v.

### ISSUE THREAD

**Issue by Onlyy-Vinh** [AaronZ345/StyleSinger#1]

**Comment by AaronZ345** [comment]
Hi, you can find detailed information regarding the architecture and baseline comparison experiments in our paper: https://arxiv.org/abs/2312.10741. In traditional SVS models, RMSSinger outperforms DiffSinger because its diffusion-based modeling of F0 allows it to produce more expressive vocals, avoiding the flatness often associated with DiffSinger. In contrast to StyleSinger, DiffSinger does not incorporate F0 modeling or style information, making it less capable of modeling detailed vocal styles such as vibrato, pronunciation, and articulation skills. Additionally, DiffSinger lacks the design of generalized modules, which limits its ability to achieve strong zero-shot performance and makes it unsuitable for style transfer tasks, such as customizing vocals with personal voice characteristics.
